spring.application.name=studentDetails

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email Configuration (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google Sheets ID Configuration
google.sheet.master-id=${SHEET_MASTER_ID}
google.sheet.auth-master-id=${SHEET_AUTH_MASTER_ID}
google.sheet.weekly-mock-id=${SHEET_WEEKLY_MOCK_ID}
google.sheet.weekly-gut-exam-id=${SHEET_WEEKLY_GUT_EXAM_ID}
google.sheet.mock-drive-id=${SHEET_MOCK_DRIVE_ID}

# Subject Mappings
google.sheet.subject.core-java=${SHEET_SUBJECT_CORE_JAVA}
google.sheet.subject.mysql=
google.sheet.subject.html=
google.sheet.subject.css=
google.sheet.subject.javascript=
google.sheet.subject.servlets=
google.sheet.subject.spring=
google.sheet.subject.spring-boot=
google.sheet.subject.microservices=
google.sheet.subject.react=
